---
repos:
- repo: https://github.com/terraform-docs/terraform-docs
  rev: v0.20.0
  hooks:
  - id: terraform-docs-go
    args: [markdown, table, --output-file, docs/README.md, ./]
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.99.0
  hooks:
  - id: terraform_fmt
  - id: terraform_validate
    args:
    - --args=-json
    - --args=-no-color
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b
  hooks:
  # Git style
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: check-vcs-permalinks
  - id: forbid-new-submodules
  - id: no-commit-to-branch

  # Common errors
  - id: end-of-file-fixer
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
    exclude: CHANGELOG.md
  - id: check-yaml
  - id: check-merge-conflict
  - id: check-executables-have-shebangs

  # Security
  - id: detect-aws-credentials
    args:
    - --allow-missing-credentials
  - id: detect-private-key

  # Detect hardcoded secrets
- repo: https://github.com/gitleaks/gitleaks
  rev: 47218a628da59ef6b24197d15f4b0248ca87f4f0    # frozen: v8.27.2
  hooks:
  - id: gitleaks

# YAML
- repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
  rev: 8d1b9cadaf854cb25bb0b0f5870e1cc66a083d6b    # frozen: 0.2.3
  hooks:
  - id: yamlfmt
    args:
    - --mapping=2
    - --sequence=2
    - --offset=0
    - --width=100

- repo: https://github.com/adrienverge/yamllint.git
  rev: 79a6b2b1392eaf49cdd32ac4f14be1a809bbd8f7    # frozen: v1.37.1
  hooks:
  - id: yamllint
    types:
    - file
    - yaml
    args:
    - --strict
    indentation: disable

# Bash
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 38980559e3a605691d6579f96222c30778e5a69e    # frozen: 3.0.0
  hooks:
  - id: shfmt
    args:
    - -l
    - -i
    - '2'
    - -ci
    - -sr
    - -w
  - id: shellcheck
