---
name: Apply
'on':
  push:
    branches:
      - apply

permissions: write-all

jobs:
  apply:
    strategy:
      matrix:
        workspaces: [development]
    uses: GrabAByte/github-devops-workflows/.github/workflows/terraformApply.yml@v1.1.0
    secrets:
      account: ${{ secrets.AWS_ACCOUNT }}
      role: ${{ secrets.AWS_ROLE }}
    with:
      region: eu-west-2
      terraformPath: .
      terraformVars: environment/${{ matrix.workspaces }}/terraform.tfvars
      workspace: ${{ matrix.workspaces }}
