---
name: CD
on:
  push:
    branches:
    - main

permissions: write-all

jobs:
  # unable to use workflow_dispatch with re-usable workflows so must auto-trigger on merge
  apply:
    strategy:
      matrix:
        workspaces: [development]
    uses: GrabAByte/github-devops-workflows/.github/workflows/terraformApply.yml@v1.1.0
    secrets:
      account: ${{ secrets.AWS_ACCOUNT }}
      role: ${{ secrets.AWS_ROLE }}
    with:
      region: eu-west-2
      terraformPath: .
      terraformVars: environment/${{ matrix.workspaces }}/terraform.tfvars
      workspace: ${{ matrix.workspaces }}

  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
    - name: Check out the codebase.
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/${{ secrets.AWS_ROLE }}
        aws-region: eu-west-2

    - name: Test
      run: |

        # initialize
        terraform init && \
        terraform workspace select development && \

        # smoke test
        API_URL=$(terraform output -raw api_url)
        IMAGE_FILE="tom-richards.jpg"
        BEARER_TOKEN=$(shuf -er -n16 {a..z} {0..9} | tr -d '\n')

        cd ./test && \
        ./api-call.sh "${API_URL}" "${IMAGE_FILE}" "${BEARER_TOKEN}"

    needs: [apply]

  semantic-release:
    uses: GrabAByte/github-devops-workflows/.github/workflows/semanticRelease.yml@v1.1.0
    needs: [apply, test]

  # destroy:
  #   strategy:
  #     matrix:
  #       workspaces: [development]
  #   uses: GrabAByte/github-devops-workflows/.github/workflows/terraformDestroy.yml@v1.1.0
  #   secrets:
  #     account: ${{ secrets.AWS_ACCOUNT }}
  #     role: ${{ secrets.AWS_ROLE }}
  #   with:
  #     region: eu-west-2
  #     terraformPath: .
  #     terraformVars: environment/${{ matrix.workspaces }}/terraform.tfvars
  #     workspace: ${{ matrix.workspaces }}
  #   needs: [apply, test]
