---
name: CI
'on':
  pull_request:

permissions: write-all

jobs:
  lint:
    uses: GrabAByte/github-devops-workflows/.github/workflows/terraformLint.yml@v1.3.0
    with:
      terraformPath: .
  validate:
    uses: GrabAByte/github-devops-workflows/.github/workflows/terraformValidate.yml@v1.3.0
    secrets:
      account: ${{ secrets.AWS_ACCOUNT }}
      role: ${{ secrets.AWS_ROLE }}
    with:
      region: eu-west-2
      terraformPath: .
    needs: [lint]
  scan:
    uses: GrabAByte/github-devops-workflows/.github/workflows/terraformScan.yml@v1.3.0
    with:
      terraformPath: .
    needs: [lint,validate]
  plan:
    strategy:
      matrix:
        include:
          - workspace: development
            account: AWS_ACCOUNT_DEV
            role: AWS_ROLE_DEV
          - workspace: pre-production
            account: AWS_ACCOUNT_PRE
            role: AWS_ROLE_PRE
          - workspace: production
            account: AWS_ACCOUNT_PROD
            role: AWS_ROLE_PROD
    uses: GrabAByte/github-devops-workflows/.github/workflows/terraformPlan.yml@v1.3.0
    secrets:
      account: ${{ secrets[matrix.account] }}
      role: ${{ secrets[matrix.role] }}
    with:
      region: eu-west-2
      terraformPath: .
      terraformVars: environment/${{ matrix.workspace }}/terraform.tfvars
      workspace: ${{ matrix.workspace }}
    needs: [lint,validate,scan]
