---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main

permissions: write-all

jobs:
  lint:
    uses: GrabAByte/github-devops-workflows/.github/workflows/terraformLint.yml@v1.1.0
    with:
      terraformPath: .
  validate:
    uses: GrabAByte/github-devops-workflows/.github/workflows/terraformValidate.yml@v1.1.0
    secrets:
      account: ${{ secrets.AWS_ACCOUNT }}
      role: ${{ secrets.AWS_ROLE }}
    with:
      region: eu-west-2
      terraformPath: .
    needs: [lint]
  scan:
    uses: GrabAByte/github-devops-workflows/.github/workflows/terraformScan.yml@v1.1.0
    with:
      terraformPath: .
    needs: [lint,validate]
  plan:
    strategy:
      matrix:
        workspaces: [development, pre-production, production]
    uses: GrabAByte/github-devops-workflows/.github/workflows/terraformPlan.yml@v1.1.0
    secrets:
      account: ${{ secrets.AWS_ACCOUNT }}
      role: ${{ secrets.AWS_ROLE }}
    with:
      region: eu-west-2
      terraformPath: .
      terraformVars: environment/${{ matrix.workspaces }}/terraform.tfvars
      workspace: ${{ matrix.workspaces }}
    needs: [lint,validate,scan]
